[project]
name = "lang-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sukanya V S", email = "sukanyas@xminds.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "langchain>=1.4.3",
    "langchain-anthropic>=1.7.5",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.6",
    "langchain-openai>=1.6.7",
    "langchain-openapi>=0.1.1",
    "langgraph>=1.2.13",
    "ollama>=0.6.3",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
lang-course = "lang_course:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
